- hosts: all
  sudo: yes
  remote_user: vagrant

  tasks:
  - name: Actualizacion
    command: sudo apt-get update

  - name: Instalar Python
    command: sudo apt-get -y install python python3

  - name: Instalar Pip
    command: sudo apt-get install python-pip python3-pip

  - name: Instalar Git
    command: sudo apt-get install git
