- hosts: all
  sudo: yes
  remote_user: vagrant

  tasks:
  - name: Actualizacion
    become: true
    command: apt-get update

  - name: Instalar Python
    become: true
    command: apt-get install python3 python

  - name: Instalar Pip
    become: true
    command: apt-get install python3-pip python3-setuptools

  - name: Instalar Git
    become: true
    command: apt-get install git

  - name: Actualizar pip
    command: pip3 install --upgrade pip

  - name: Instalar Requerimientos
    command: pip3 install -r ProyectoIV-BOT/requirements.txt








